# Generated by Django 6.0.2 on 2026-02-12 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='cities', to=settings.AUTH_USER_MODEL),
        ),
    ]
