# Generated by Django 6.0.2 on 2026-02-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_city_name_city_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
