# Generated by Django 6.0.2 on 2026-02-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_city_lat_city_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='send_time',
            field=models.TimeField(null=True),
        ),
    ]
