# Generated by Django 6.0.2 on 2026-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_send_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='send_time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mailing_interval',
            field=models.IntegerField(default=24, help_text='Interval in hours'),
        ),
    ]
