# Generated by Django 6.0.2 on 2026-02-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_send_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_notified',
            field=models.DateTimeField(blank=True, help_text='The last time the user was notified about the weather', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive weather updates (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mailing_interval',
            field=models.IntegerField(default=24, help_text='Interval in hours', null=True),
        ),
    ]
